// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExperimentalFeatures
{
    static class Vsix
    {
        public const string Id = "d9fa18a5-26f3-4900-9275-19e0cd5dcd9f";
        public const string Name = "Experimental Web Tools";
        public const string Description = @"Contains experimental features from the Visual Studio Web Team";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Microsoft";
        public const string Tags = "extensions, features, preview";
    }
}
