// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExperimentalFeatures
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidShowModalCommandPackageString = "a24cb156-c6c8-4f54-822b-fa76687e138d";
        public const string guidShowModalCommandPackageCmdSetString = "42a66f9d-2139-4459-b7d9-8b8ba8f03dfe";
        public static Guid guidShowModalCommandPackage = new Guid(guidShowModalCommandPackageString);
        public static Guid guidShowModalCommandPackageCmdSet = new Guid(guidShowModalCommandPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ShowModalCommandId = 0x0100;
    }
}
